In [2]:
import numpy 
import pandas as pd
from GetTaskSimilarityAlgorithm1 import Algorithm1_Get_task_to_task_similarity
from GetWorkerObservedAccuracy import Get_Worker_Observed_Accuracy


In [3]:
task_df =  pd.read_csv('C:/Users/Arwa/Desktop/datasets/Ex2/Jobs_dataset_tokenized_Ex2.csv')

similarity_matrix_df = pd.DataFrame()

for i in range (0,10):
     for j in range (0,10):
        Sim = Algorithm1_Get_task_to_task_similarity(task_df.loc[i],task_df.loc[j])
        similarity_matrix_df.loc[task_df.loc[i, 'TaskID'], task_df.loc[j, 'TaskID']] = Sim



similarity of titles: 1.0
skills of t1: Required_Skills 1     Banner Design
Required_Skills 2    Graphic Design
Required_Skills 3       Logo Design
Required_Skills 4         Photoshop
Required_Skills 5    Website Design
Name: 0, dtype: object
skills of t2: Required_Skills 1     Banner Design
Required_Skills 2    Graphic Design
Required_Skills 3       Logo Design
Required_Skills 4         Photoshop
Required_Skills 5    Website Design
Name: 0, dtype: object
sim_list [[1.0, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
max of sim [1.0, 1.0, 1.0]
sim_list [[0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0]

sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [1.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
max of sim [1.0, 1.0, 1.0]
sim_list [[0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [1.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [1.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
max of sim [1.0, 1.0, 1.0]
sim_list [[0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [1.0, 1.0, 1.0]]
max of sim [1.0, 1.0, 1.0]
maximum similarity list [0.5, 1.0, 1.0, 1.0, 1.0]
similarity of titles: 0.14438355527738672
skills of t1: Required_Skills 1     Banner Design
Required_Skills 2    Graphic Design
Required_Skills 3       Logo Design


sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [0.0, 1.0, 1.0]
maximum similarity list [0.0, 0.0, 0.0, 0.0, 0.0]
similarity of titles: 0.22028815056182968
skills of t1: Required_Skills 1    Graphic Design
Required_Skills 2        Illstrator
Required_Skills 3       Logo Design
Required_Skills 4         Photoshop
Required_Skills 5               NaN
Name: 1, dtype: object
skills of t2: Required_Skills 1     Banner Design
Required_Skills 2    Graphic Design
Required_Skills 3       Logo Design
Required_Skills 4         Photoshop
Required_Skills 5    Website Design
Name: 0, dtype: object
sim_list [[0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0,

sim_list [[0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [1.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [1.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [1.0, 1.0, 1.0]
sim_list [[0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [1.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
max of sim [1.0, 1.0, 1.0]
sim_list [[0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
max of sim [0.5, 1.0, 1.0]
maxi

sim_list [[1.0, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
max of sim [1.0, 1.0, 1.0]
maximum similarity list [1.0]
similarity of titles: 0.0
skills of t1: Required_Skills 1    Graphic Design
Required_Skills 2               NaN
Required_Skills 3               NaN
Required_Skills 4               NaN
Required_Skills 5               NaN
Name: 2, dtype: object
skills of t2: Required_Skills 1     Banner Design
Required_Skills 2    Graphic Design
Required_Skills 3        Illstrator
Required_Skills 4       Logo Design
Required_Skills 5    Website Design
Name: 5, dtype: object
sim_list [[0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0], [0

sim_list [[0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
max of sim [1.0, 1.0, 1.0]
maximum similarity list [1.0]
similarity of titles: 1.0
skills of t1: Required_Skills 1     Banner Design
Required_Skills 2    Graphic Design
Required_Skills 3         Photoshop
Required_Skills 4        Prestashop
Required_Skills 5    Website Design
Name: 3, dtype: object
skills of t2: Required_Skills 1     Banner Design
Required_Skills 2    Graphic Design
Required_Skills 3         Photoshop
Required_Skills 4        Prestashop
Required_Skills 5    Website Design
Name: 3, dtype: object
sim_list [[1.0, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0

sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [0.5, 1.0, 1.0]
sim_list [[0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [0.5, 1.0, 1.0]
maximum similarity list [0.5, 0.5, 0.5]
similarity of titles: 0.0
skills of t1: Required_Skills 1           Compter Secrity
Required_Skills 2    Network Administration
Required_Skills 3                       NaN
Required_Skills 4                       NaN
Required_Skills 5                       NaN
Name: 8, dtype: object
skills of t2: Required_Skills 1     Bann

sim_list [[0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
max of sim [1.0, 1.0, 1.0]
sim_list [[0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [0.0, 1.0, 1.0]
sim_list [[0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
max of sim [0.5, 1.0, 1.0]
sim_

sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [0.0, 1.0, 1.0]
maximum similarity list [0.0, 0.0, 0.0]
similarity of titles: 0.0
skills of t1: Required_Skills 1           Compter Secrity
Required_Skills 2    Network Administration
Required_Skills 3                       NaN
Required_Skills 4                       NaN
Required_Skills 5                       NaN
Name: 8, dtype: object
skills of t2: Required_Skills 1    Graphic Design
Required_Skills 2        Illstrator
Required_Skills 3       Logo Design
Required_Skills 4         Photoshop
Required_Skills 5    Website Design
Name: 4, dtype: object
sim_list [[0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [0.0, 1.0, 1.0]
sim_li

Name: 5, dtype: object
skills of t2: Required_Skills 1     Banner Design
Required_Skills 2    Graphic Design
Required_Skills 3         Photoshop
Required_Skills 4        Prestashop
Required_Skills 5    Website Design
Name: 3, dtype: object
sim_list [[1.0, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
max of sim [1.0, 1.0, 1.0]
sim_list [[0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
max of sim [1.0, 1.0, 1.0]
sim_list [[0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0]

sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [0.0, 1.0, 1.0]
sim_list [[0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [0.0, 1.0, 1.0]
maximum similarity list [0.0, 0.0, 0.0]
similarity of titles: 0.0
skills of t1: Required_Skills 1           Compter Secrity
Required_Skills 2    Network Administration
Required_Skills 3                       NaN
Required_Skills 4                       NaN
Required_Skills 5                       NaN
Name: 8, dtype: object
skills of t2: Required_Skills 1     Banner Design
Required_Skills 2    Graphic Desig

sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [0.0, 1.0, 1.0]
sim_list [[0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [0.0, 1.0, 1.0]
maximum similarity list [0.0, 0.0]
similarity of titles: 0.0
skills of t1: Required_Skills 1    Asterisk PBX
Required_Skills 2            Linx
Required_Skills 3             NaN
Required_Skills 4             NaN
Required_Skills 5             NaN
Name: 6, dtype: object
skills of t2: Required_Skills 1     Banner Design
Required_Skills 2    Graphic Design
Required_Skills 3        Illstrator
Required_Skills 4       Logo Design
Required_Skills 5    Website Design
Name: 

sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [0.0, 1.0, 1.0]
maximum similarity list [0.0]
similarity of titles: 0.0
skills of t1: Required_Skills 1                     Cisco
Required_Skills 2    Network Administration
Required_Skills 3                   OpenVMS
Required_Skills 4                       NaN
Required_Skills 5                       NaN
Name: 7, dtype: object
skills of t2: Required_Skills 1     Banner Design
Required_Skills 2    Graphic Design
Required_Skills 3         Photoshop
Required_Skills 4        Prestashop
Required_Skills 5    Website Design
Name: 3, dtype: object
sim_list [[0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [0.5, 1.0, 1.0]
sim_list [[0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.

sim_list [[1.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [1.0, 1.0, 1.0]
sim_list [[0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [0.5, 1.0, 1.0]
sim_list [[0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [0.5, 1.0, 1.0]
maximum similarity list [1.0, 0.5, 0.5]
similarity of titles: 0.0
skills of t1: Required_Skills 1           Compter Secrity
Required_Skills 2    Network Administration
Required_Skills 3                       NaN
Re

sim_list [[0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [1.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
max of sim [1.0, 1.0, 1.0]
maximum similarity list [0.0, 1.0]
similarity of titles: 1.0000000000000004
skills of t1: Required_Skills 1           Compter Secrity
Required_Skills 2    Network Administration
Required_Skills 3                       NaN
Required_Skills 4                       NaN
Required_Skills 5                       NaN
Name: 8, dtype: object
skills of t2: Required_Skills 1           Compter Secrity
Required_Skills 2    Network Administration
Required_Skills 3                       NaN
Required_Skills 4                       NaN
Required_Skills 5                       NaN
Name: 8, dtype: object
sim_list [[1.0000000000000002, 1.0, 1.0]]
sim_list [[1.0000000000000002, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [1.0000000000000002, 1.0, 1.0]
sim_list [[0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
max of sim [1.0, 1.0, 1.0]
maximum si

sim_list [[0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [0.5, 1.0, 1.0]
sim_list [[0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [0.0, 1.0, 1.0]
maximum similarity list [0.5, 0.0, 0.5, 0.5, 0.0]
similarity of titles: 0.0
skills of t1: Required_Skills 1          Cisco
Required_Skills 2    Engineering
Required_Skills 3     Javascript
Required_Skills 4            PHP
Required_Skills 5    Web Secrity
Name: 9, dtype: object
skills of t2: Required_Skills 1    Graphic Design
Required

sim_list [[0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
max of sim [0.5, 1.0, 1.0]
maximum similarity list [0.33609692727625756, 0.5]
similarity of titles: 1.0000000000000002
skills of t1: Required_Skills 1          Cisco
Required_Skills 2    Engineering
Required_Skills 3     Javascript
Required_Skills 4            PHP
Required_Skills 5    Web Secrity
Name: 9, dtype: object
skills of t2: Required_Skills 1          Cisco
Required_Skills 2    Engineering
Required_Skills 3     Javascript
Required_Skills 4            PHP
Required_Skills 5    Web Secrity
Name: 9, dtype: object
sim_list [[1.0, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.0, 1.0, 1.

In [4]:
Sim = Algorithm1_Get_task_to_task_similarity(task_df.loc[0],task_df.loc[4])
print(Sim)

similarity of titles: 0.1707761131901165
skills of t1: Required_Skills 1     Banner Design
Required_Skills 2    Graphic Design
Required_Skills 3       Logo Design
Required_Skills 4         Photoshop
Required_Skills 5    Website Design
Name: 0, dtype: object
skills of t2: Required_Skills 1    Graphic Design
Required_Skills 2        Illstrator
Required_Skills 3       Logo Design
Required_Skills 4         Photoshop
Required_Skills 5    Website Design
Name: 4, dtype: object
sim_list [[0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[0.5, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0], [0.5, 1.0, 1.0]]
max of sim [0.5, 1.0, 1.0]
sim_list [[1.0, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.0, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0]]
sim_list [[1.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.5, 1.0, 1.0], 

In [5]:
print(similarity_matrix_df)

     t0   t1   t2   t3   t4   t5   t6   t7   t8   t9
t0  1.0  0.6  0.8  0.7  0.7  0.7  0.0  0.0  0.0  0.0
t1  0.6  1.0  0.8  0.4  0.7  0.6  0.0  0.0  0.0  0.0
t2  0.8  0.8  1.0  0.7  0.7  0.7  0.0  0.0  0.0  0.0
t3  0.7  0.4  0.7  1.0  0.5  0.5  0.2  0.4  0.2  0.1
t4  0.6  0.7  0.7  0.5  1.0  0.8  0.0  0.0  0.0  0.0
t5  0.6  0.6  0.7  0.5  0.8  1.0  0.0  0.0  0.0  0.0
t6  0.0  0.0  0.0  0.2  0.0  0.0  1.0  0.2  0.2  0.2
t7  0.0  0.0  0.0  0.4  0.0  0.0  0.2  1.0  0.4  0.5
t8  0.0  0.0  0.0  0.2  0.0  0.0  0.2  0.4  1.0  0.3
t9  0.0  0.0  0.0  0.2  0.0  0.0  0.2  0.5  0.3  1.0


In [6]:
S =  similarity_matrix_df.values
print(S)

[[1.  0.6 0.8 0.7 0.7 0.7 0.  0.  0.  0. ]
 [0.6 1.  0.8 0.4 0.7 0.6 0.  0.  0.  0. ]
 [0.8 0.8 1.  0.7 0.7 0.7 0.  0.  0.  0. ]
 [0.7 0.4 0.7 1.  0.5 0.5 0.2 0.4 0.2 0.1]
 [0.6 0.7 0.7 0.5 1.  0.8 0.  0.  0.  0. ]
 [0.6 0.6 0.7 0.5 0.8 1.  0.  0.  0.  0. ]
 [0.  0.  0.  0.2 0.  0.  1.  0.2 0.2 0.2]
 [0.  0.  0.  0.4 0.  0.  0.2 1.  0.4 0.5]
 [0.  0.  0.  0.2 0.  0.  0.2 0.4 1.  0.3]
 [0.  0.  0.  0.2 0.  0.  0.2 0.5 0.3 1. ]]


In [7]:
n = numpy.sqrt(S.size) # get S matrix size (float)
n = int(n) # make it integer
D = numpy.zeros((n,n)) # set array elements to zero

In [8]:
# create the diagonal matrix 

In [9]:
# Computing the Diagonal matrix D
for i in range(0,n):
    for j in range(0,n):
        D[i][i] = D[i][i] + S[i][j]

In [10]:
D

array([[4.7, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 4.4, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 5.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 4.5, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 4.5, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 4.5, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 3. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 3.1, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 3.5, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 2.5]])

In [11]:
# Computing the Normalized similarity
Sdash = numpy.zeros((n,n))  # declaration
D_tpomh = numpy.zeros((n,n))  # D to the power of minus 1/2

In [12]:
"""----the diagonal matrix to the power of -1/2-----"""
"""------ compute the inverse of D"""
for i in range(0, n):
    for j in range(0, n):
        D_tpomh[i][i] = 1/numpy.sqrt(D[i][i])   # only diagonal elements

In [13]:
D_tpomh

array([[0.4612656 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.47673129, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.44280744, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.47140452, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.47140452,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.47140452, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.57735027, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.       

In [14]:
"""-----the normalized Similarity ------"""
Sdash = D_tpomh @ S @ D_tpomh

In [15]:
Sdash

array([[0.21276596, 0.13193985, 0.10212592, 0.15220988, 0.15220988,
        0.15220988, 0.02663118, 0.        , 0.04931137, 0.058346  ],
       [0.15392982, 0.22727273, 0.10555008, 0.11236664, 0.1573133 ,
        0.13483997, 0.02752409, 0.        , 0.05096472, 0.03015113],
       [0.16340147, 0.16888013, 0.19607843, 0.146119  , 0.146119  ,
        0.146119  , 0.051131  , 0.        , 0.02366905, 0.0280056 ],
       [0.15220988, 0.11236664, 0.08349657, 0.22222222, 0.13333333,
        0.13333333, 0.05443311, 0.02677398, 0.05039526, 0.05962848],
       [0.15220988, 0.13483997, 0.08349657, 0.13333333, 0.22222222,
        0.15555556, 0.02721655, 0.        , 0.05039526, 0.05962848],
       [0.15220988, 0.11236664, 0.08349657, 0.13333333, 0.15555556,
        0.22222222, 0.05443311, 0.        , 0.05039526, 0.05962848],
       [0.02663118, 0.05504819, 0.0255655 , 0.08164966, 0.05443311,
        0.05443311, 0.33333333, 0.09837388, 0.09258201, 0.10954451],
       [0.        , 0.02707652, 0.       

In [29]:
worker_df = pd.read_csv('C:/Users/Arwa/Desktop/datasets/Ex2/Freelancer_dataset_Ex2.csv')
task_df = pd.read_csv('C:/Users/Arwa/Desktop/datasets/Ex2/Jobs_dataset_tokenized_Ex2.csv')
worker_Ob_Acc_df = pd.DataFrame()
for i in range (0,10):
        worker_Ob_Acc_df.loc[worker_df.loc[1,'name'],task_df.loc[i, 'TaskID']] = \
            Get_Worker_Observed_Accuracy(worker_df.loc[1],task_df.loc[i])

task category graphic design
Tcat = 284 Tw = 5
task category graphic design
Tcat = 284 Tw = 5
task category graphic design
Tcat = 284 Tw = 5
task category graphic design
Tcat = 284 Tw = 5
task category Graphic Design
Tcat = 166 Tw = 1
task category graphic design
Tcat = 284 Tw = 5


In [20]:
worker_Ob_Acc_df

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>t0</th>
      <th>t1</th>
      <th>t2</th>
      <th>t3</th>
      <th>t4</th>
      <th>t5</th>
      <th>t6</th>
      <th>t7</th>
      <th>t8</th>
      <th>t9</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>@AaRTMART</th>
      <td>0.086268</td>
      <td>0.086268</td>
      <td>0.086268</td>
      <td>0.086268</td>
      <td>0.029518</td>
      <td>0.086268</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
  </tbody>
</table>
</div>

In [37]:
def trimAllColumns(df):
    """
    Trim whitespace from ends of each value across all series in dataframe
    """
    trimStrings = lambda x: x.strip() if type(x) is str else x
    return df.applymap(trimStrings)
# ----- Give the value of Zero for unperformed tasks
if worker_df.loc[1,'name'] != task_df.loc[1,'Freelancer_username']:
    q = 0

else:
    combined_df = pd.read_csv('C:/Users/Arwa/Desktop/datasets/Ex2/jobs_and_freelancers_combined_Ex2.csv')
    combined_df = trimAllColumns(combined_df)
    #take the worker history  -------------------
    worker_his_df = combined_df.loc[combined_df['name'] == worker_df.loc[1,'name']]

    # the number of performed tasks in the same category as t in worker profile
    worker_cat_no_task = worker_his_df.groupby('Job_Category').size()
    TwCat = worker_cat_no_task[task_df.loc[1,'Job_Category']]

    # the number of tasks in the task performed task category  -------------------
    task_df = pd.read_csv('C:/Users/Arwa/Desktop/datasets/Ex1/Jobs_dataset_tokenized_Ex1.csv')
    task_df.fillna('')


    cat_no_task = task_df.groupby('Job_Category').size()

    Tcat = cat_no_task[task_df.loc[1,'Job_Category']]
    print('task category', task_df.loc[1,'Job_Category'])
    rating = worker_df.loc[1,'rating']




    if Tcat == 0:
        Tcat = 1

    print('Tcat =', Tcat, 'Tw =', TwCat)
    q = (rating/5) *0.001

print('q = ' , q)

task category graphic design
Tcat = 284 Tw = 5
q =  0.0009800000000000002
